version: '3.7'

services:
  web:
    container_name: blogdriven_web
    build: .
    #command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8300:8300"
    depends_on:
      - db
  db:
    container_name: blogdriven_db
    image: postgres
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: blogdrivendb
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - "5435:5432"
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - pgadmin:/home/app/.pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    
    restart: always

  nginx:
    container_name: blogdriven_nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  pgadmin:
